<?php
$CNRS = array(
//0=> array("titre" => "Evolutionary Ecology", "rang" => "toto"),
1=> array("titre" => "@GRH", "rang" => "0"),
2=> array("titre" => "ACCOMEX", "rang" => "0"),
3=> array("titre" => "ACM Transactions on Algorithms", "rang" => "0"),
4=> array("titre" => "Acta Endoscopica", "rang" => "0"),
5=> array("titre" => "Actualité et dossier en santé publique", "rang" => "0"),
6=> array("titre" => "Advances in Consumer Research", "rang" => "H"),
7=> array("titre" => "Advances in Management Accounting", "rang" => "0"),
8=> array("titre" => "Agribusiness", "rang" => "4"),
9=> array("titre" => "Algorithmica", "rang" => "0"),
10=> array("titre" => "Alternatives économiques Poche", "rang" => "0"),
11=> array("titre" => "American Economic Review", "rang" => "1"),
12=> array("titre" => "American Journal of Agricultural Economics", "rang" => "1"),
13=> array("titre" => "American Journal of Public Health", "rang" => "H"),
14=> array("titre" => "Analyse und Kritik", "rang" => "0"),
15=> array("titre" => "Annales de la Faculté de Droit - Economie et Administration de Metz", "rang" => "0"),
16=> array("titre" => "Annales d'économie et de statistique", "rang" => "2"),
17=> array("titre" => "Annals of Economics and Finance", "rang" => "E"),
18=> array("titre" => "Annals of Economics and Statistics", "rang" => "2"),
19=> array("titre" => "Annals of Regional Science", "rang" => "2"),
20=> array("titre" => "Antitrust Bulletin", "rang" => "2"),
21=> array("titre" => "Applied Economics", "rang" => "2"),
22=> array("titre" => "Applied Economics Letters", "rang" => "4"),
23=> array("titre" => "Applied Financial Economics", "rang" => "4"),
24=> array("titre" => "Arxius de ciències socials", "rang" => "0"),
25=> array("titre" => "B.E. Journal of Macroeconomics", "rang" => "E"),
26=> array("titre" => "Bankers, Markets and Investors", "rang" => "3"),
27=> array("titre" => "Banque et Marchés", "rang" => "3"),
28=> array("titre" => "Behavioral and Brain Sciences", "rang" => "0"),
29=> array("titre" => "Biotechnologie, Agronomie, Société et Environnement", "rang" => "0"),
30=> array("titre" => "Bretagnes", "rang" => "0"),
31=> array("titre" => "British Food Journal", "rang" => "0"),
32=> array("titre" => "Brussels economic review Cahiers économiques de Bruxelles", "rang" => "4"),
33=> array("titre" => "Bulletin Épidémiologique Hebdomadaire", "rang" => "0"),
34=> array("titre" => "Bulletin officiel de la Concurrence, de la Consommation et de la Répression des fraudes", "rang" => "0"),
35=> array("titre" => "Cahiers de la Sécurité", "rang" => "0"),
36=> array("titre" => "Cahiers de l'audition", "rang" => "0"),
37=> array("titre" => "Cahiers d'Économie Politique", "rang" => "3"),
38=> array("titre" => "Cahiers français", "rang" => "0"),
39=> array("titre" => "Canadian Journal of Regional Science", "rang" => "3"),
40=> array("titre" => "Climatic Change", "rang" => "3"),
41=> array("titre" => "Communication et organisation", "rang" => "0"),
42=> array("titre" => "Communications and Strategies", "rang" => "4"),
43=> array("titre" => "Comptabilité Contrôle Audit", "rang" => "2"),
44=> array("titre" => "Concurrences", "rang" => "4"),
45=> array("titre" => "Connaissance de l'Emploi", "rang" => "0"),
46=> array("titre" => "Constitutional Political Economy", "rang" => "E"),
47=> array("titre" => "Cuadernos de Gestión", "rang" => "0"),
48=> array("titre" => "Culture études", "rang" => "0"),
49=> array("titre" => "Décisions Marketing", "rang" => "4"),
50=> array("titre" => "Defence and Peace Economics", "rang" => "E"),
51=> array("titre" => "Diagnostic", "rang" => "0"),
52=> array("titre" => "Digiworld Economic Journal", "rang" => "0"),
53=> array("titre" => "Distribución y Consumo", "rang" => "0"),
54=> array("titre" => "Distributed Computing", "rang" => "0"),
55=> array("titre" => "Droit et gestion des collectivités territoriales", "rang" => "0"),
56=> array("titre" => "Ecological Economics", "rang" => "1"),
57=> array("titre" => "Economia Global e Gestao / Global Economics and Management Review", "rang" => "0"),
58=> array("titre" => "Economic Analysis", "rang" => "E"),
59=> array("titre" => "Economic and Industrial Democracy", "rang" => "E"),
60=> array("titre" => "Economic Inquiry", "rang" => "2"),
61=> array("titre" => "Economic Modelling", "rang" => "2"),
62=> array("titre" => "Economic Record", "rang" => "3"),
63=> array("titre" => "Economic Systems", "rang" => "3"),
64=> array("titre" => "Economic Theory", "rang" => "1"),
65=> array("titre" => "Economica", "rang" => "2"),
66=> array("titre" => "Economics and Politics", "rang" => "3"),
67=> array("titre" => "Economics Bulletin", "rang" => "3"),
68=> array("titre" => "Economics Letters", "rang" => "3"),
69=> array("titre" => "Economics of Innovation and New Technology", "rang" => "2"),
70=> array("titre" => "Economics of Transition", "rang" => "2"),
71=> array("titre" => "Economics: The Open-Access, Open-Assessment E-Journal", "rang" => "E"),
72=> array("titre" => "Économie Appliquée", "rang" => "4"),
73=> array("titre" => "Économie et Humanisme", "rang" => "0"),
74=> array("titre" => "Économie et Prévision", "rang" => "3"),
75=> array("titre" => "Économie et Sociétés, Série \"Histoire de la pensée économique\"", "rang" => "4"),
76=> array("titre" => "Economie et Statistique", "rang" => "3"),
77=> array("titre" => "Économie internationale", "rang" => "3"),
78=> array("titre" => "Economie Publique", "rang" => "4"),
79=> array("titre" => "Économie rurale", "rang" => "4"),
80=> array("titre" => "Économies et Sociétés", "rang" => "E"),
81=> array("titre" => "Economies et Sociétés, série \"Systèmes Agroalimentaires\"", "rang" => "0"),
82=> array("titre" => "Économies et Sociétés, série AF: \"Histoire économique quantitative\"", "rang" => "0"),
83=> array("titre" => "Education Economics", "rang" => "E"),
84=> array("titre" => "Éducation permanente", "rang" => "0"),
85=> array("titre" => "Ekonomiaz", "rang" => "E"),
86=> array("titre" => "Electoral Studies", "rang" => "0"),
87=> array("titre" => "Empirica", "rang" => "E"),
88=> array("titre" => "Empirical Economics", "rang" => "4"),
89=> array("titre" => "Energy Policy", "rang" => "2"),
90=> array("titre" => "Entreprendre et Innover", "rang" => "0"),
91=> array("titre" => "Entrepreneurship and Regional Development", "rang" => "3"),
92=> array("titre" => "Entrepreneurship Theory and Practice", "rang" => "1"),
93=> array("titre" => "Environmental and Resource Economics", "rang" => "2"),
94=> array("titre" => "Environmetrics", "rang" => "0"),
95=> array("titre" => "Espace populations sociétés", "rang" => "0"),
96=> array("titre" => "études foncières", "rang" => "0"),
97=> array("titre" => "Euro Asia Journal of Management", "rang" => "0"),
98=> array("titre" => "European Economic Review", "rang" => "1"),
99=> array("titre" => "European Journal of Gastroenterology & Hepatology", "rang" => "0"),
100=> array("titre" => "European Journal of Health Economics", "rang" => "2"),
101=> array("titre" => "European Journal of International Management", "rang" => "H"),
102=> array("titre" => "European Journal of Law and Economics", "rang" => "2"),
103=> array("titre" => "European Journal of Operational Research", "rang" => "1"),
104=> array("titre" => "European Journal of Political Economy", "rang" => "3"),
105=> array("titre" => "European Journal of Public Health", "rang" => "3"),
106=> array("titre" => "European Journal of the History of Economic Thought", "rang" => "2"),
107=> array("titre" => "European Management Journal", "rang" => "3"),
108=> array("titre" => "European Retail Research", "rang" => "0"),
109=> array("titre" => "European Review of Agricultural Economics", "rang" => "2"),
110=> array("titre" => "Experimental Economics", "rang" => "1"),
111=> array("titre" => "Fikr", "rang" => "0"),
112=> array("titre" => "Finance", "rang" => "2"),
113=> array("titre" => "Finance Contrôle Stratégie", "rang" => "3"),
114=> array("titre" => "Finances hospitalières", "rang" => "0"),
115=> array("titre" => "Fiscal studies", "rang" => "3"),
116=> array("titre" => "Fisheries Research", "rang" => "0"),
117=> array("titre" => "Food Quality and Preference", "rang" => "0"),
118=> array("titre" => "Forest Policy and Economics", "rang" => "0"),
119=> array("titre" => "Formation Emploi", "rang" => "4"),
120=> array("titre" => "Games and Economic Behavior", "rang" => "1"),
121=> array("titre" => "Geneva Papers on Risk and Insurance", "rang" => "3"),
122=> array("titre" => "Geneva Risk and Insurance Review", "rang" => "2"),
123=> array("titre" => "Géographie, Economie, Société", "rang" => "4"),
124=> array("titre" => "Gérer et Comprendre. Annales des Mines", "rang" => "4"),
125=> array("titre" => "Gérontologie et société", "rang" => "0"),
126=> array("titre" => "Gestion", "rang" => "0"),
127=> array("titre" => "Gestion 2000", "rang" => "0"),
128=> array("titre" => "Gestion et finances publiques", "rang" => "0"),
129=> array("titre" => "Gestion, revue internationale de gestion", "rang" => "4"),
130=> array("titre" => "Gestions hospitalières", "rang" => "0"),
131=> array("titre" => "Global Journal of Health Science", "rang" => "0"),
132=> array("titre" => "Group Decision and Negotiation", "rang" => "H"),
133=> array("titre" => "GUT", "rang" => "0"),
134=> array("titre" => "Health Economics", "rang" => "1"),
135=> array("titre" => "Health Policy", "rang" => "2"),
136=> array("titre" => "History of Economic Ideas", "rang" => "3"),
137=> array("titre" => "History of political economy", "rang" => "1"),
138=> array("titre" => "Homo Oeconomicus", "rang" => "E"),
139=> array("titre" => "Humanisme et Entreprise", "rang" => "0"),
140=> array("titre" => "Idées", "rang" => "0"),
141=> array("titre" => "IEEE Transactions on Intelligent Transportation Systems Technology Planning and Operations", "rang" => "0"),
142=> array("titre" => "Indian Growth and Development Review", "rang" => "E"),
143=> array("titre" => "Indigo. Humanities magazine for young people", "rang" => "0"),
144=> array("titre" => "Industrial and Labor Relations Review", "rang" => "1"),
145=> array("titre" => "Industry and Innovation", "rang" => "3"),
146=> array("titre" => "Información Comercial Española - Revista de Economía", "rang" => "0"),
147=> array("titre" => "Information Economics and Policy", "rang" => "2"),
148=> array("titre" => "Informations sociales", "rang" => "0"),
149=> array("titre" => "INNOVAR, Journal of Administrative and Social Sciences", "rang" => "0"),
150=> array("titre" => "Intelligences Journal", "rang" => "0"),
151=> array("titre" => "International Business Research", "rang" => "E"),
152=> array("titre" => "International Employment Relations Review", "rang" => "0"),
153=> array("titre" => "International Food and Agribusiness Management Review", "rang" => "E"),
154=> array("titre" => "International Game Theory Review", "rang" => "3"),
155=> array("titre" => "International Journal of Arts Management", "rang" => "4"),
156=> array("titre" => "International Journal of Biomedical Engineering and Technology", "rang" => "0"),
157=> array("titre" => "International Journal of Business", "rang" => "E"),
158=> array("titre" => "International Journal of Electronic Commerce", "rang" => "2"),
159=> array("titre" => "International Journal of Emerging Markets", "rang" => "0"),
160=> array("titre" => "International Journal of Game Theory", "rang" => "2"),
161=> array("titre" => "International Journal of Health Care Finance and Economics", "rang" => "2"),
162=> array("titre" => "International Journal of Hospitality Management", "rang" => "H"),
163=> array("titre" => "International Journal of Industrial Organization", "rang" => "1"),
164=> array("titre" => "International Journal of Innovation Management", "rang" => "4"),
165=> array("titre" => "International Journal of Intercultural Relations", "rang" => "H"),
166=> array("titre" => "International Journal of Internet Marketing and Advertising", "rang" => "0"),
167=> array("titre" => "International Journal of Logistics Management, The", "rang" => "3"),
168=> array("titre" => "International Journal of Management Concepts and Philosophy", "rang" => "0"),
169=> array("titre" => "International Journal of Manpower", "rang" => "3"),
170=> array("titre" => "International Journal of Multicriteria Decision Making", "rang" => "0"),
171=> array("titre" => "International Journal of Nonprofit and Voluntary Sector Marketing", "rang" => "0"),
172=> array("titre" => "International Journal of Open Source Software & Processes", "rang" => "0"),
173=> array("titre" => "International Journal of Production Economics", "rang" => "1"),
174=> array("titre" => "International Journal of Retail and Distribution Management", "rang" => "3"),
175=> array("titre" => "International Journal of Sport Finance", "rang" => "E"),
176=> array("titre" => "International Journal of Technology Assessment in Health Care", "rang" => "0"),
177=> array("titre" => "International Journal of the Economics of Business", "rang" => "3"),
178=> array("titre" => "International Journal of Wine Business Research", "rang" => "0"),
179=> array("titre" => "International Journal of Work Organisation and Emotion", "rang" => "0"),
180=> array("titre" => "international journal on foodsystem dynamics", "rang" => "0"),
181=> array("titre" => "International Labour Review", "rang" => "3"),
182=> array("titre" => "International Management", "rang" => "0"),
183=> array("titre" => "International Review of Applied Economics", "rang" => "4"),
184=> array("titre" => "International Review of Financial Analysis", "rang" => "3"),
185=> array("titre" => "International Review of Law and Economics", "rang" => "1"),
186=> array("titre" => "International Review of Retail, Distribution and Consumer Research", "rang" => "0"),
187=> array("titre" => "International Scientific Journal of Management Information Systems", "rang" => "0"),
188=> array("titre" => "International Tax and Public Finance", "rang" => "2"),
189=> array("titre" => "Journal d'Economie Médicale", "rang" => "4"),
190=> array("titre" => "Journal for Studies in Economics and Econometrics", "rang" => "E"),
191=> array("titre" => "Journal Frontiers in Finance and Economics", "rang" => "0"),
192=> array("titre" => "Journal of Agricultural and Food Industrial Organization", "rang" => "3"),
193=> array("titre" => "Journal of Applied Business Research", "rang" => "3"),
194=> array("titre" => "Journal of Applied Management Accounting Research", "rang" => "0"),
195=> array("titre" => "Journal of Asset Management", "rang" => "4"),
196=> array("titre" => "Journal of Banking and Finance", "rang" => "2"),
197=> array("titre" => "Journal of Business", "rang" => "E"),
198=> array("titre" => "Journal of Business Ethics", "rang" => "2"),
199=> array("titre" => "Journal of Business Research", "rang" => "2"),
200=> array("titre" => "Journal of Chinese Economic and Foreign Trade Studies", "rang" => "E"),
201=> array("titre" => "Journal of Conflict Resolution", "rang" => "E"),
202=> array("titre" => "Journal of Corporate Finance", "rang" => "2"),
203=> array("titre" => "Journal of Corporate Ownership and Control", "rang" => "0"),
204=> array("titre" => "Journal of Cultural Economics", "rang" => "3"),
205=> array("titre" => "Journal of Derivatives", "rang" => "3"),
206=> array("titre" => "Journal of derivatives and Hedge Funds", "rang" => "E"),
207=> array("titre" => "Journal of Development Economics", "rang" => "1"),
208=> array("titre" => "Journal of Economic Behavior and Organization", "rang" => "2"),
209=> array("titre" => "Journal of Economic Geography", "rang" => "1"),
210=> array("titre" => "Journal of Economic Inequality", "rang" => "3"),
211=> array("titre" => "Journal of Economic Issues", "rang" => "3"),
212=> array("titre" => "Journal of Economic Psychology", "rang" => "3"),
213=> array("titre" => "Journal of Economic Theory", "rang" => "1"),
214=> array("titre" => "Journal of Financial Economic Policy", "rang" => "E"),
215=> array("titre" => "Journal of Financial Transformation", "rang" => "E"),
216=> array("titre" => "Journal of Fixed Income", "rang" => "3"),
217=> array("titre" => "Journal of Global Strategic Management", "rang" => "0"),
218=> array("titre" => "Journal of Health Economics", "rang" => "1"),
219=> array("titre" => "Journal of Industrial Economics", "rang" => "1"),
220=> array("titre" => "Journal of innovation economics", "rang" => "0"),
221=> array("titre" => "Journal of Intelligence Studies in Business", "rang" => "0"),
222=> array("titre" => "Journal of Intelligent Transportation Systems: Technology, Planning, and Operations", "rang" => "0"),
223=> array("titre" => "Journal of Interconnection Networks", "rang" => "0"),
224=> array("titre" => "Journal of International Money and Finance", "rang" => "2"),
225=> array("titre" => "Journal of Internet Banking and Commerce", "rang" => "0"),
226=> array("titre" => "Journal of Marketing Channels", "rang" => "H"),
227=> array("titre" => "Journal of Marketing Trends", "rang" => "0"),
228=> array("titre" => "Journal of Mathematical Economics", "rang" => "1"),
229=> array("titre" => "Journal of Modern Accounting and Auditing", "rang" => "0"),
230=> array("titre" => "Journal of Money, Credit and Banking", "rang" => "1"),
231=> array("titre" => "Journal of Multi-Criteria Decision Analysis", "rang" => "4"),
232=> array("titre" => "Journal of Population Economics", "rang" => "2"),
233=> array("titre" => "Journal of Public Economic Theory", "rang" => "2"),
234=> array("titre" => "Journal of Public Economics", "rang" => "1"),
235=> array("titre" => "Journal of Public Finance and Public Choice", "rang" => "4"),
236=> array("titre" => "Journal of Public Health", "rang" => "0"),
237=> array("titre" => "Journal of Regional Science", "rang" => "2"),
238=> array("titre" => "Journal of Regulatory Economics", "rang" => "2"),
239=> array("titre" => "Journal of Retailing and Consumer Services", "rang" => "3"),
240=> array("titre" => "Journal of Risk and Uncertainty", "rang" => "2"),
241=> array("titre" => "Journal of risk management in financial institutions", "rang" => "0"),
242=> array("titre" => "Journal of Small Business Management", "rang" => "2"),
243=> array("titre" => "Journal of Social Management", "rang" => "0"),
244=> array("titre" => "Journal of Socio-Economics", "rang" => "4"),
245=> array("titre" => "Journal of the History of Economic Thought", "rang" => "2"),
246=> array("titre" => "Journal of the Operational Research Society", "rang" => "2"),
247=> array("titre" => "Journal of Theoretical Politics", "rang" => "0"),
248=> array("titre" => "Journal of Transport Economics and Policy", "rang" => "2"),
249=> array("titre" => "Journal of wine economics", "rang" => "3"),
250=> array("titre" => "Kybernetika", "rang" => "0"),
251=> array("titre" => "Kyklos", "rang" => "2"),
252=> array("titre" => "La Lettre de l'OCIM (Office de Coopération et d'Information Muséographique)", "rang" => "0"),
253=> array("titre" => "La Recherche", "rang" => "0"),
254=> array("titre" => "La Revue des Sciences de Gestion, Direction et Gestion", "rang" => "0"),
255=> array("titre" => "Labour Economics", "rang" => "2"),
256=> array("titre" => "L'Actualité économique", "rang" => "4"),
257=> array("titre" => "Lecturas de Economia", "rang" => "E"),
258=> array("titre" => "Les cahiers du management territorial", "rang" => "0"),
259=> array("titre" => "Logistique et Management", "rang" => "0"),
260=> array("titre" => "Macroeconomic Dynamics", "rang" => "2"),
261=> array("titre" => "Maghreb et sciences sociales", "rang" => "0"),
262=> array("titre" => "Management Decision", "rang" => "4"),
263=> array("titre" => "Management et avenir", "rang" => "4"),
264=> array("titre" => "Management et Sciences Sociales", "rang" => "0"),
265=> array("titre" => "Management International", "rang" => "3"),
266=> array("titre" => "Management Learning", "rang" => "3"),
267=> array("titre" => "Management Science", "rang" => "1"),
268=> array("titre" => "Managerial and Decision Economics", "rang" => "3"),
269=> array("titre" => "Manchester School", "rang" => "3"),
270=> array("titre" => "Marketing ZFP Journal of Research and Management", "rang" => "0"),
271=> array("titre" => "Mathematical Methods of Operations Research", "rang" => "3"),
272=> array("titre" => "Mathematical Social Sciences", "rang" => "2"),
273=> array("titre" => "Médecine", "rang" => "0"),
274=> array("titre" => "Medical Decision Making", "rang" => "2"),
275=> array("titre" => "National Tax Journal", "rang" => "2"),
276=> array("titre" => "Omega", "rang" => "3"),
277=> array("titre" => "Open Economies Review", "rang" => "3"),
278=> array("titre" => "Outlook on Agriculture", "rang" => "0"),
279=> array("titre" => "Pacific Economic Review", "rang" => "3"),
280=> array("titre" => "Papers in Regional Science", "rang" => "2"),
281=> array("titre" => "PharmacoEconomics", "rang" => "2"),
282=> array("titre" => "Philosophical Transactions of the Royal Society", "rang" => "0"),
283=> array("titre" => "Physica A", "rang" => "0"),
284=> array("titre" => "Politiques et management public", "rang" => "4"),
285=> array("titre" => "Pouvoirs locaux", "rang" => "0"),
286=> array("titre" => "Premières Informations Premières Synthèses", "rang" => "0"),
287=> array("titre" => "Pricladnaya econometrica (Econométrie appliquée)", "rang" => "0"),
288=> array("titre" => "Problèmes économiques", "rang" => "0"),
289=> array("titre" => "Procedia - Social and Behavioral Sciences", "rang" => "0"),
290=> array("titre" => "Psychologie du travail et des organisations", "rang" => "0"),
291=> array("titre" => "Public Choice", "rang" => "1"),
292=> array("titre" => "Quaderni", "rang" => "0"),
293=> array("titre" => "Quadrature", "rang" => "0"),
294=> array("titre" => "Quantitative Finance", "rang" => "3"),
295=> array("titre" => "Rand Journal of Economics", "rang" => "1"),
296=> array("titre" => "Réalités industrielles. Annales des mines", "rang" => "0"),
297=> array("titre" => "Recherche et Applications en Marketing", "rang" => "2"),
298=> array("titre" => "Recherches Économiques de Louvain", "rang" => "3"),
299=> array("titre" => "Recherches en Sciences de Gestion", "rang" => "0"),
300=> array("titre" => "REDES-Revista hispana para el análisis de redes sociales", "rang" => "0"),
301=> array("titre" => "Reflets et Perspectives de la vie économique", "rang" => "0"),
302=> array("titre" => "Regards croisés sur l'économie", "rang" => "0"),
303=> array("titre" => "Région et Développement", "rang" => "4"),
304=> array("titre" => "Regional Science and Urban Economics", "rang" => "2"),
305=> array("titre" => "Regional studies", "rang" => "2"),
306=> array("titre" => "Relief - Echanges du Céreq", "rang" => "0"),
307=> array("titre" => "Research and Practice in Human Resource Management", "rang" => "0"),
308=> array("titre" => "Research in Economics", "rang" => "3"),
309=> array("titre" => "Research Policy", "rang" => "2"),
310=> array("titre" => "Réseaux", "rang" => "4"),
311=> array("titre" => "Review of Accounting and Finance", "rang" => "4"),
312=> array("titre" => "Review of Development Economics", "rang" => "4"),
313=> array("titre" => "Review of Economics and Statistics", "rang" => "1"),
314=> array("titre" => "Review of Industrial Organization", "rang" => "2"),
315=> array("titre" => "Review of Institution and Economics", "rang" => "0"),
316=> array("titre" => "Review of International Economics", "rang" => "2"),
317=> array("titre" => "Review of International Organizations", "rang" => "4"),
318=> array("titre" => "Review of Network Economics", "rang" => "3"),
319=> array("titre" => "Revista Calidad en la Educación", "rang" => "0"),
320=> array("titre" => "Revue de Gestion des Ressources Humaines", "rang" => "3"),
321=> array("titre" => "Revue de l'Entrepreneuriat", "rang" => "4"),
322=> array("titre" => "Revue de l'OFCE", "rang" => "4"),
323=> array("titre" => "Revue de l'Organisation Responsable", "rang" => "4"),
324=> array("titre" => "Revue d'Économie Financière", "rang" => "4"),
325=> array("titre" => "Revue d'Économie Industrielle", "rang" => "3"),
326=> array("titre" => "Revue d'Economie Méridionale", "rang" => "0"),
327=> array("titre" => "Revue d'Économie Politique", "rang" => "3"),
328=> array("titre" => "Revue d'Économie Régionale et Urbaine", "rang" => "3"),
329=> array("titre" => "Revue des Nouvelles Technologies de l'Information", "rang" => "0"),
330=> array("titre" => "Revue d'Études en Agriculture et Environnement", "rang" => "4"),
331=> array("titre" => "Revue du Financier ", "rang" => "0"),
332=> array("titre" => "Revue du M.A.U.S.S.", "rang" => "0"),
333=> array("titre" => "Revue économique", "rang" => "3"),
334=> array("titre" => "Revue Economique et Sociale", "rang" => "0"),
335=> array("titre" => "Revue Espace", "rang" => "0"),
336=> array("titre" => "Revue Française de Comptabilité", "rang" => "0"),
337=> array("titre" => "Revue Française de Finances Publiques", "rang" => "0"),
338=> array("titre" => "Revue Française de Gestion", "rang" => "4"),
339=> array("titre" => "Revue Française de Gestion des Ressources Humaines", "rang" => "0"),
340=> array("titre" => "Revue Française de Gestion Industrielle", "rang" => "4"),
341=> array("titre" => "Revue Française de Socio-Économie", "rang" => "E"),
342=> array("titre" => "Revue Française d'Administration Publique", "rang" => "4"),
343=> array("titre" => "Revue Française d'Économie", "rang" => "3"),
344=> array("titre" => "Revue Française du Marketing", "rang" => "0"),
345=> array("titre" => "Revue internationale de droit économique", "rang" => "3"),
346=> array("titre" => "Revue Internationale de Psychosociologie", "rang" => "0"),
347=> array("titre" => "Revue internationale de psychosociologie et de gestion des comportements organisationnels", "rang" => "0"),
348=> array("titre" => "Revue Internationale du Travail", "rang" => "0"),
349=> array("titre" => "Revue internationale P.M.E.", "rang" => "4"),
350=> array("titre" => "Revue Libanaise de Gestion et d'Economie", "rang" => "0"),
351=> array("titre" => "Revue trimestrielle de Droit Financier", "rang" => "0"),
352=> array("titre" => "Risques", "rang" => "0"),
353=> array("titre" => "Santé RH", "rang" => "0"),
354=> array("titre" => "Sasin Journal of Management", "rang" => "0"),
355=> array("titre" => "Sciences de gestion", "rang" => "4"),
356=> array("titre" => "Scientific, social and business journal -Energy Policy", "rang" => "0"),
357=> array("titre" => "Small Business Economics", "rang" => "2"),
358=> array("titre" => "Social Choice and Welfare", "rang" => "1"),
359=> array("titre" => "Sociologie Santé", "rang" => "0"),
360=> array("titre" => "Southern Economic Journal", "rang" => "2"),
361=> array("titre" => "Spatial Economic Analysis", "rang" => "4"),
362=> array("titre" => "Statistics and Computing", "rang" => "0"),
363=> array("titre" => "Storia del Pensiero Economico", "rang" => "E"),
364=> array("titre" => "Strategic Change", "rang" => "3"),
365=> array("titre" => "Strategic Management Journal", "rang" => "1"),
366=> array("titre" => "Technological Forecasting and Social Change", "rang" => "2"),
367=> array("titre" => "Telecommunications Policy", "rang" => "4"),
368=> array("titre" => "The B.E. Journal of Theoretical Economics", "rang" => "0"),
369=> array("titre" => "The European Journal of Comparative Economics", "rang" => "3"),
370=> array("titre" => "The Review of International Organizations", "rang" => "4"),
371=> array("titre" => "The Sociological Quarterly", "rang" => "0"),
372=> array("titre" => "Theoretical Computer Science", "rang" => "0"),
373=> array("titre" => "Theory and Decision", "rang" => "2"),
374=> array("titre" => "Theory of Computing Systems", "rang" => "0"),
375=> array("titre" => "tic & société", "rang" => "0"),
376=> array("titre" => "Tiers Monde", "rang" => "0"),
377=> array("titre" => "Time and Society", "rang" => "0"),
378=> array("titre" => "Timisoara Journal of Economics", "rang" => "0"),
379=> array("titre" => "Tourism Analysis", "rang" => "H"),
380=> array("titre" => "Travail et Emploi", "rang" => "4"),
381=> array("titre" => "Urban Public Economics Review", "rang" => "4"),
382=> array("titre" => "Urban Studies", "rang" => "2"),
383=> array("titre" => "Vie et sciences économiques", "rang" => "E"),
384=> array("titre" => "World Bank Economic Review", "rang" => "1"),
385=> array("titre" => "World Economics", "rang" => "0"),
386=> array("titre" => "World Economy", "rang" => "2"),
387=> array("titre" => "Zeitschrift für Sozialmanagement", "rang" => "0")
);
?>